"""
Django settings for app project.

Generated by 'django-admin startproject' using Django 4.2.7.
For more information, see:
https://docs.djangoproject.com/en/4.2/topics/settings/
"""

import os
from pathlib import Path

# ---- БАЗОВЫЙ ПУТЬ ПРОЕКТА ----
# Path(__file__).resolve() – получает путь к текущему файлу (settings.py)
# .parent.parent – поднимается на два уровня вверх, чтобы получить корень проекта
BASE_DIR = Path(__file__).resolve().parent.parent

# ---- СЕКРЕТНЫЙ КЛЮЧ (для подписей сессий, токенов) ----
# В продакшене НИКОГДА не хранить в коде, использовать переменные окружения!
SECRET_KEY = 'django-insecure-ld)8k$gfoow^#9-6mm@palg6l9d)&l!5ng#m2@=msxhq353g#2'

# ---- РЕЖИМ ОТЛАДКИ ----
# True – показывает подробные ошибки, False – скрывает (для продакшена)
DEBUG = True

# ---- РАЗРЕШЁННЫЕ ХОСТЫ ----
# '*' – разрешает любые домены (только для разработки!)
ALLOWED_HOSTS = ['*']

# ---- УСТАНОВЛЕННЫЕ ПРИЛОЖЕНИЯ ----
# Список всех активных приложений Django
INSTALLED_APPS = [
    'django.contrib.admin',          # административная панель
    'django.contrib.auth',           # система аутентификации
    'django.contrib.contenttypes',   # работа с типами контента
    'django.contrib.sessions',       # сессии
    'django.contrib.messages',       # сообщения (flash-сообщения)
    'django.contrib.staticfiles',    # работа со статическими файлами (CSS, JS, картинки)
    'django.contrib.postgres',       # дополнительные возможности для PostgreSQL

    "debug_toolbar",                 # панель отладки (показывает SQL-запросы, время и т.д.)

    # Собственные приложения проекта
    'main',     # главное приложение (главная страница, общие шаблоны)
    'goods',    # приложение товаров (основное для конфигуратора)
    'users',    # приложение пользователей
    'carts',    # корзина
    'orders',   # заказы
]

# ---- ПРОМЕЖУТОЧНЫЕ СЛОИ (MIDDLEWARE) ----
# Обрабатывают запросы до и после выполнения представлений
MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',          # безопасность
    'django.contrib.sessions.middleware.SessionMiddleware',   # управление сессиями
    'django.middleware.common.CommonMiddleware',              # общие обработчики (например, слеши в URL)
    'django.middleware.csrf.CsrfViewMiddleware',              # защита от CSRF-атак
    'django.contrib.auth.middleware.AuthenticationMiddleware', # аутентификация пользователя
    'django.contrib.messages.middleware.MessageMiddleware',    # сообщения
    'django.middleware.clickjacking.XFrameOptionsMiddleware',  # защита от кликджекинга

    "debug_toolbar.middleware.DebugToolbarMiddleware",        # отладочная панель
]

# ---- КОРНЕВОЙ URL-КОНФИГ ----
ROOT_URLCONF = 'app.urls'

# ---- ШАБЛОНЫ ----
TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],    # папка с общими шаблонами (на уровне проекта)
        'APP_DIRS': True,                    # искать шаблоны в папках templates каждого приложения
        'OPTIONS': {
            'context_processors': [          # процессоры контекста – добавляют данные во все шаблоны
                'django.template.context_processors.debug',
                'django.template.context_processors.request', # добавляет объект request в шаблоны
                'django.contrib.auth.context_processors.auth', # добавляет user
                'django.contrib.messages.context_processors.messages', # добавляет сообщения
            ],
        },
    },
]

# ---- WSGI (для развертывания) ----
WSGI_APPLICATION = 'app.wsgi.application'

# ---- БАЗА ДАННЫХ (PostgreSQL) ----
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',  # используем PostgreSQL
        'NAME': 'home',           # имя базы данных
        'USER': 'home',           # пользователь
        'PASSWORD': 'home',       # пароль
        'HOST': 'localhost',      # хост (локальный)
        'PORT': '5432',           # стандартный порт PostgreSQL
    }
}

# ---- КЭШ (файловый) ----
# Хранит кэш в папке cache/ в корне проекта
CACHES = {
    "default": {
        "BACKEND": "django.core.cache.backends.filebased.FileBasedCache",
        "LOCATION": BASE_DIR / "cache",
    }
}

# ---- ВАЛИДАЦИЯ ПАРОЛЕЙ ----
# Набор проверок для паролей пользователей (используется при регистрации)
AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

# ---- ИНТЕРНАЦИОНАЛИЗАЦИЯ ----
LANGUAGE_CODE = 'ru'           # язык интерфейса – русский
TIME_ZONE = 'UTC'              # часовой пояс (можно изменить на 'Europe/Moscow')
USE_I18N = True                # включена поддержка перевода
USE_TZ = True                  # использовать временные зоны

# ---- СТАТИЧЕСКИЕ ФАЙЛЫ (CSS, JS, картинки для верстки) ----
# URL-префикс, по которому будут доступны статические файлы (например, /static/css/style.css)
STATIC_URL = 'static/'

# Дополнительные папки, где Django ищет статику (помимо папок static внутри приложений)
STATICFILES_DIRS = [
    BASE_DIR / 'static'        # папка static в корне проекта
]

# ---- МЕДИА-ФАЙЛЫ (загруженные пользователями, например, изображения товаров) ----
# URL-префикс для медиа-файлов (например, /media/goods_images/server_1u.jpg)
MEDIA_URL = 'media/'

# Абсолютный путь на диске, куда сохраняются загруженные файлы
MEDIA_ROOT = BASE_DIR / 'media'

# ---- НАСТРОЙКА ДЛЯ ЗАГЛУШКИ КАРТИНОК ТОВАРОВ (ДОБАВЛЕНО ВРУЧНУЮ) ----
# Путь к картинке-заглушке ОТНОСИТЕЛЬНО STATIC_URL.
# Например, если файл лежит в static/images/no_image.jpg, то значение 'images/no_image.jpg'.
DEFAULT_PRODUCT_IMAGE = 'deps/images/no_image.png'

# ---- НАСТРОЙКА DEBUG_TOOLBAR ----
# IP-адреса, с которых разрешён доступ к отладочной панели
INTERNAL_IPS = [
    "127.0.0.1",   # локальный компьютер
]

# ---- ПРОЧИЕ НАСТРОЙКИ ----
DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'   # тип поля для первичных ключей по умолчанию
AUTH_USER_MODEL = 'users.User'                         # кастомная модель пользователя (из приложения users)
LOGIN_URL = '/user/login/'                             # URL для страницы входа
LOGIN_REDIRECT_URL = '/'                               # куда перенаправлять после входа