# Generated by Django 4.2.7 on 2026-08-30 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0003_alter_categories_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='form_factor',
            field=models.CharField(choices=[('1U', '1U'), ('2U', '2U'), ('3U', '3U'), ('4U', '4U'), ('5U', '5U'), ('OPEN_FRAME', 'Open Frame')], default='1U', max_length=20, verbose_name='Форм-фактор'),
        ),
    ]
